### ISSUE TITLE
retrieve transactions in cents

### ISSUE THREAD

**Issue by flokli** [figo-connect/php-figo#11]
According to the [figo docs](http://docs.figo.io/#api-calls56), you can request the transaction amounts to be transmitted in cents.

However, this is not possible using the PHP Bindings, [as the needed parameter is missing](https://github.com/figo-connect/php-figo/blob/master/figo/Account.php#L86).

Could you please include it?

**Comment by berend** [comment]
Yes, we will add this. (Also sorry for the late reply!)

**Comment by visioncode** [comment]
@berend I updated composer a few hours ago and noticed that something is going wrong .. all my new transaction values were multiplied by 100. At the history of the latest version I noticed this change here. Before this update, all values were returned in cents by default (please correct me if I'm wrong). With this update, all values are without cents now. Am I the only user who got problems with this? Is this behaviour wanted? :)

**Comment by berend** [comment]
Looking into this

**Comment by berend** [comment]
This is not only an issue with the SDK, but with the API itself. We will release a fix/workaround for the SDK soon and also work on fixing the API issue.

I will close this once again the fix is live on packagist. Version https://packagist.org/packages/figo/figo#1.1.6 should work in the mean time.

**Comment by berend** [comment]
@visioncode we just released https://packagist.org/packages/figo/figo#1.1.8, this should fix the issue.

Can you confirm?

**Comment by berend** [comment]
seems to be ok
