### ISSUE TITLE
Count > ~150 breaks GET Transactions with multiple Accounts

### ISSUE THREAD

**Issue by rbarisic** [figo-connect/php-figo#26]
This error is pretty odd.

Request URL: https://api.figo.me/rest/transactions?count=200&sort=asc

If you set the offset higher than 0, this request is OK
If you set the offset to 0, this request returns "HTTPInternalServerError"

If you set the count lower than ~150, this request is OK
If you set the count higher than ~150, this request returns "HTTPInternalServerError"

if you set the count higher than 200, but add an offset, this request returns "HTTPInternalServerError"

This ONLY happens if the access tokens allows access to multiple Bank Accounts.

**Comment by piotrowski** [comment]
This is more a general API bug, not related to php-figo, correct?

**Comment by berend** [comment]
I am trying to reproduce this. It is not php-sdk related but nontheless, if that is reproducable to might have triggered a bug.

What I did so far:
* create a new user, connect 3 banks, giving me in total ~230 transactions
* get an access_token
* calling `https://api.figo.me/rest/transactions?offset=0&count=200&sort=asc` gives me a `200 OK`
* calling `https://api.figo.me/rest/transactions?offset=199&count=200&sort=asc` gives me a `200 OK`
* calling `https://api.figo.me/rest/transactions?offset=201&count=200&sort=asc` gives me a `200 OK`
* calling `https://api.figo.me/rest/transactions?offset=-1&count=200&sort=asc` gives me a `200 OK` (we might want to think about that one)
* calling `https://api.figo.me/rest/transactions?count=-1&sort=asc` gives me a `200 OK` (we might want to think about that one, too)

Calling with counts higher than 200 also looks good. So currently I am not able to reproduce that. Does this still happen?

**Comment by berend** [comment]
seems to be ok by now. If not - repoen
