### ISSUE TITLE
Bug with new Category class

### ISSUE THREAD

**Issue by visioncode** [figo-connect/php-figo#35]
Today I updated my figo-php to the newest version. This error occurs:

A PHP Error was encountered
Severity: Compile Error
Message: Cannot use [] for reading
Filename: figo/Base.php
Line Number: 56

Line 56:
`$this->$key[] = new Category($session, $category);`

**Comment by berend** [comment]
should be fixed in https://packagist.org/packages/figo/figo#1.1.8
