### ISSUE TITLE
stream_socket_client(): unable to connect to tlsv1.2://api.figo.me:443/

### ISSUE THREAD

**Issue by visioncode** [figo-connect/php-figo#37]
I upgraded from php 5 to php 7 and noticed the above error message.

On php5 everything works fine, php 7 results in a warning:

Severity: Warning
Message: stream_socket_client(): unable to connect to tlsv1.2://api.figo.me:443/ (Failed to parse address "api.figo.me:443/")
Filename: figo/HttpsRequest.php
Line Number: 69

When I remove the trailing slash it works fine at php 5 AND php 7. Is there any reason for this trailing slash?

**Comment by samuelvogel** [comment]
It's a bug, see #34.

**Comment by berend** [comment]
solved by #34
