### ISSUE TITLE
packagist is still on old version

### ISSUE THREAD

**Issue by ribb3r** [figo-connect/php-figo#49]
Hi,

packagist doesn't show current version (3.1.1). See: https://packagist.org/packages/figo/figo

Thank you.

**Comment by christianhuening** [comment]
will take a look

**Comment by ribb3r** [comment]
Any update on this issue? Thank you.

**Comment by christianhuening** [comment]
![Bildschirmfoto 2019-03-29 um 10 07 42](https://user-images.githubusercontent.com/738953/55221744-82da3580-520a-11e9-96a9-b2c4e1ef9952.png)

working on it

**Comment by christianhuening** [comment]
@ribb3r 3.1.1 is in packageist now
